---
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: mirror to github
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:toolcreator/greenums.git
      ssh_key:
        from_secret: ssh_key
